#define   BOARD     D501
#include<tv_boards.c>  
unsigned int8 i,j;
unsigned int32 Y,K;
void main()
{
      system_init();  
      while(true)
      {
         for(i=0;i<10;i++)
         {
            led32.ledx32=~led32.ledx32;
            led32_display();
            delay_ms(500);
         }
         for(j=0;j<2;j++)
         {
            Y=0x00000000;
            for(i=0;i<32;i++)
            {
               Y=(Y<<1)|0x00000001;
               led32.ledx32=Y;
               led32_display();
               delay_ms(50);
            }
            for(i=0;i<32;i++)
            {
               Y=Y<<1;
               led32.ledx32=Y;
               led32_display();
               delay_ms(50);
            }
         }
         for(i=0;i<10;i++)
         {
            led32.ledx32=~led32.ledx32;
            led32_display();
            delay_ms(500);
         }
         for(j=0;j<2;j++)
         {
            Y=0x00000000;
            for(i=0;i<32;i++)
            {
               Y=(Y>>1)|0x80000000;
               led32.ledx32=Y;
               led32_display();
               delay_ms(50);
            }
            for(i=0;i<32;i++)
            {
               Y=Y>>1;
               led32.ledx32=Y;
               led32_display();
               delay_ms(50);
            }
         }
         for(i=0;i<10;i++)
         {
            led32.ledx32=~led32.ledx32;
            led32_display();
            delay_ms(500);
         }
         for(j=0;j<2;j++)
         {
            Y=0x0000;
            K=0X0000;
            for(i=0;i<16;i++)
            {
               Y=(Y>>1)|0x8000;
               K=(K<<1)|0X0001;
               led32.ledx16[1]=Y;
               led32.ledx16[0]=K;
               led32_display();
               delay_ms(50);
            }
            for(i=0;i<16;i++)
            {
               Y=Y>>1;
               K=K<<1;
               led32.ledx16[1]=Y;
               led32.ledx16[0]=K;
               led32_display();
               delay_ms(50);
            }
         }
         for(i=0;i<10;i++)
         {
            led32.ledx32=~led32.ledx32;
            led32_display();
            delay_ms(500);
         }
         for(j=0;j<2;j++)
         {
            Y=0x0000;
            K=0X0000;
            for(i=0;i<16;i++)
            {
               Y=(Y<<1)|0x0001;
               K=(K>>1)|0X8000;
               led32.ledx16[1]=Y;
               led32.ledx16[0]=K;
               led32_display();
               delay_ms(50);
            }
            for(i=0;i<16;i++)
            {
               Y=Y<<1;
               K=K>>1;
               led32.ledx16[1]=Y;
               led32.ledx16[0]=K;
               led32_display();
               delay_ms(50);
            }
         }
      }
}
